### ISSUE TITLE
Support for check-model-has-one-of-tests-by-name

### ISSUE THREAD

**Issue by jtalmi** [dbt-checkpoint/dbt-checkpoint#5]
**Describe the feature you'd like**
Many dbt projects require at least one unique test per model. However, this test may be one of several flavors, e.g.:
- test_unique
- test_unique_where
- test_unique_threshold
- test_unique_combination_of_columns

Initial thought: We could leverage some sort of "OR" functionality, e.g.

`test_unique | test_unique_where = 1`

**Comment by tomsej** [comment]
Thank you @jtalmi for a great idea. I am definitely for implementing this hook. I would rather use 2 arguments - `test_names` and `min_test_cnt` (or `test_cnt`) then one with some OR functionality `test_unique | test_unique_where = 1` since parsing with Argparse would be too complicated. E.g.:

```
--test-names test_unique test_unique_where --test-ct = 1
```
What do you think?

**Comment by jtalmi** [comment]
yep, i like that. going to take a stab at that now.

**Comment by tomsej** [comment]
Closed in #6

**Comment by ConstantinoSchillebeeckx** [comment]
For anyone that lands here, you can reference tests like [dbt_utils.unique_combination_of_columns](https://github.com/dbt-labs/dbt-utils#unique_combination_of_columns-source) with `unique_combination_of_columns`
